spring:
  datasource:
    # 指定数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置数据库url
    url: jdbc:mysql://localhost:3306/endless?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    # 配置数据库驱动 mysql8.0以上需要.cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 连接池的配置信息
      # 初始化时建立物理连接的个数
      initial-size: 3
      # 连接池最小连接数
      min-idle: 3
      # 连接池最大连接数
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-connect-error-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      # 用来检测连接是否有效的sql 必须是一个查询语句
      # mysql中为 select 'x'
      # oracle中为 select 1 from dual
      validation-query: select 'x'
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement,mysql5.5+建议开启
      pool-prepared-statements: true
      # 当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: false
      # 配置扩展插件
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 定时输出统计信息到日志中，并每次输出日志会导致清零（reset）连接池相关的计数器。
      time-between-log-stats-millis: 300000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
  redis:
    host: 192.168.75.128
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  servlet:
    multipart:
      #上传最大文件大小。值可以使用后缀“MB”或“KB”。指示兆字节或千字节大小。
      max-file-size: 100MB
      #最大请求大小可以是mb也可以是kb
      max-request-size: 100MB
server:
  #端口
  port: 8081
  servlet:
    context-path: /
mybatis:
  #mapper的xml位置和别名
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: team.seven.endless
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  #    call-setters-on-nulls: true   #空值映射开启

#邮箱验证码有效时间/秒
code:
  expiration: 300

# 电子邮件配置
# 如果是腾讯个人qq邮箱，这里的密码不是邮箱登录密码，而是授权码：
# 授权码：网页QQ邮箱 > 设置 > 账户 > POP3/IMAP/SMTP/Exchange/CardDAV/CalDAV服务 > 开启STMP并获得授权码
email:
  host: smtp.qiye.aliyun.com # SMTP地址
  port: 465
  from: 昵称<xxx@xxx.com> # 发件人昵称
  pass: xxxxxx
  user: xxx@xxx.com # 邮箱地址

# 验证码有效时长(秒)
verification:
  expiration-time: 600